### ISSUE TITLE
Training but AttributeError

### ISSUE THREAD

**Issue by Sunshine8921** [MediaBrain-SJTU/Where2comm#8]
when I want to train it, 
`(Where2comm) aitest8@9207cdaf7f93:~/Where2comm$ python opencood/tools/train.py --hypes_yaml opencood/hypes_yaml/dair-v2x/dair_early.yaml 
Dataset Building
<opencood.data_utils.datasets.early_fusion_dataset_dair.EarlyFusionDatasetDAIR object at 0x7f7139fd5b50>
Traceback (most recent call last):
  File "opencood/tools/train.py", line 190, in <module>
    main()
  File "opencood/tools/train.py", line 44, in main
    collate_fn=opencood_train_dataset.collate_batch_train,
  File "/public/home/aitest8/conda/envs/Where2comm/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 83, in __getattr__
    raise AttributeError
AttributeError`

I don't know what happen. Could you help me? 

My dataset is follow [this](https://github.com/MediaBrain-SJTU/Where2comm/issues/2#issuecomment-1306228335), but I not sure whether is true. Could you tell you more detail about the tree of DAIR-V2X?

**Comment by XJTU-Haolin** [comment]
same question. I cannot run dair-single(latefusion). V2VNet is okay.

**Comment by KKHAOO** [comment]
Have you solved the problem？

**Comment by HappyStupidChild** [comment]
> 当我想训练它时， `(Where2comm) aitest8@9207cdaf7f93:~/Where2comm$ python opencood/tools/train.py --hypes_yaml opencood/hypes_yaml/dair-v2x/dair_early.yaml Dataset Building <opencood.data_utils.datasets.early_fusion_dataset_dair.EarlyFusionDatasetDAIR object at 0x7f7139fd5b50> Traceback (most recent call last): File "opencood/tools/train.py", line 190, in <module> main() File "opencood/tools/train.py", line 44, in main collate_fn=opencood_train_dataset.collate_batch_train, File "/public/home/aitest8/conda/envs/Where2comm/lib/python3.7/site-packages/torch/utils/data/dataset.py", line 83, in __getattr__ raise AttributeError AttributeError`
> 
> 我不知道发生了什么。您能帮我吗？
> 
> 我的数据集是 follow [this](https://github.com/MediaBrain-SJTU/Where2comm/issues/2#issuecomment-1306228335)，但我不确定是否属实。您能告诉您有关 DAIR-V2X 树的更多详细信息吗？

yaml文件里配置这个就好了： core_method: 'IntermediateFusionDatasetDAIR'
